[tool.black]
line-length = 120
target-version = ['py38']
include = './src/*'
exclude = '''
/(
    \.editorconfig
  | \.git
  | \.pre-commit-config.yaml
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | Makefile
  | LICENCE
)/
'''
